name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare publish directory
        run: |
          mkdir -p publish
          cp index.html publish/
          echo "calc.yuygfgg.xyz" > publish/CNAME

      - name: Deploy to pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: publish
          user_name: GitHub Actions
          user_email: github-actions@github.com